version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
          - "eslint-plugin-*"
          - "eslint-config-*"
          - "typescript-eslint"
      safe-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      major-updates:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
